---
- name: 1password
  hosts: all

  tasks:
    - name: download 1pwd
      uri:
        url: https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
        dest: ./1pwd.deb
        creates: ./1pwd.deb
    - name: install deps
      become: true
      apt:
        pkg:
          - gnupg2
    - name: install 1pwd
      become: true
      apt:
        deb: ./1pwd.deb
