---
- name: 1pwd systemd
  hosts: all

  tasks:
    - name: setup 1pwd.service
      become: true
      template:
        src: ../templates/1pwd.service.j2
        dest: /etc/systemd/system/1pwd.service

    - name: enable 1pwd.service
      become: true
      systemd:
        name: 1pwd
        daemon_reload: true
        enabled: yes
        state: started
