---
- name: 1pwd-cli
  hosts: all

  tasks:
    - name: download
      uri:
        url: https://cache.agilebits.com/dist/1P/op/pkg/v1.12.2/op_linux_amd64_v1.12.2.zip
        dest: ./1pwd-cli.zip
        creates: ./1pwd-cli.zip
    - name: unzip
      shell: unzip -o 1pwd-cli.zip
      args:
        creates: op.sig
    - name: verify
      shell: |
        gpg \
          --keyserver hkps://keyserver.ubuntu.com \
          --receive-keys 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
        gpg --verify op.sig op
    - name: install
      become: yes
      shell: |
        mv op /usr/local/bin/op
        rm op.sig
      args:
        creates: /usr/local/bin/op
