---
- name: aws access
  hosts: all

  vars_prompt:
    - name: aws_access_key_id
      prompt: access key id
      private: yes
    - name: aws_secret_access_key
      prompt: secret access key
      private: yes
    - name: aws_region
      prompt: region
      default: eu-west-2
    - name: output_format
      prompt: output format
      default: text

  tasks:
    - name: install awscli
      homebrew:
        name: awscli
        state: present
        path: /home/linuxbrew/.linuxbrew/bin

    - name: configure awscli
      expect:
        command: aws configure
        responses:
          (?i)id: "{{ aws_access_key_id }}"
          (?i)secret: "{{ aws_secret_access_key }}"
          (?i)region: "{{ aws_region }}"
          (?i)format: "{{ output_format }}"
        creates: "$HOME/.aws/credentials"
