- name: docker-add-user
  hosts: all
  become: yes

  tasks:
    - name: add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups:
          - docker
        append: true
      notify: restart docker

  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
