---
- name: inactivity
  hosts: all
  become: true

  vars:
    location: /opt/bin
    path: /opt/bin/inactivity

  vars_prompt:
    - name: ssh_port
      default: 22

  tasks:
    - name: create {{ location }}
      file:
        path: "{{ location }}"
        state: directory

    - name: create {{ path }}
      template:
        src: ../templates/inactivity.j2
        dest: "{{ path }}"
        owner: root
        group: root
        mode: 744

    - name: setup cron job
      ansible.builtin.cron:
        name: inactivity
        minute: "*/30"
        hour: "*"
        job: "/usr/bin/bash {{ path }}"
        user: root
