---
- name: locale
  hosts: all

  roles:
    - role: oefenweb.locales
      locales_present:
        - en_GB.UTF-8
      locales_default:
        lang: en_GB.UTF-8

  # tasks:
  #   - name: Set default locale
  #     ansible.builtin.debconf:
  #       name: locales
  #       question: locales/default_environment_locale
  #       value: en_GB.UTF-8
  #       vtype: select

  #   - name: Set to generate locales
  #     ansible.builtin.debconf:
  #       name: locales
  #       question: locales/locales_to_be_generated
  #       value: en_GB.UTF-8 UTF-8
  #       vtype: multiselect
