---
- name: ssh authorised keys
  hosts: all

  tasks:
    - name: auth login from <your-device>
      ansible.posix.authorized_key:
        user: "{{ ansible_ssh_user }}"
        state: present
        key: "{{ lookup('file', '../keys/your-device.pub') }}"
